apiVersion: v1
kind: Secret
metadata:
  name: blockchain-api-secrets
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3JlczBwb3N0Z3JlczoxMjcuMC4wLjE6NTQzMi9wb3N0Z3JlcyA= # postgres://postgres:postgres@postgres:5432/postgres
  REDIS_URL: cmVkaXM6Ly9yZWRpczoxMjcuMC4wLjE6NjM3OSA= # redis://redis:127.0.0.1:6379
  KAFKA_BROKERS: a2Fma2E6MTI3LjAuMC4xOjkwOTIg# kafka:127.0.0.1:9092
  SENTRY_DSN: "" # Empty in stage
  # TLS certificates (if using rustls)
  TLS_CERT: "" # Base64 encoded certificate
  TLS_KEY: "" # Base64 encoded private key

